# -*- coding: utf-8 -*-
"""restaurant_food.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MT2rMB6dbZGPEiCdjftvP831OcVea2sQ
"""

# Authenticate and access Google Cloud services
from google.colab import auth
auth.authenticate_user()

# Import the necessary libraries
from google.cloud import storage
from google.cloud import bigquery

# First make connection to BigQuery
# Replace 'your-project-id' with your Google Cloud project ID
# Replace 'your-dataset-name' with your dataset name
project_id = "whyso-project-0621"
dataset_name = "restaurant_dataset"
table_name = "food_df" # if you make changes previously, then here you need to make according change

bigquery_client = bigquery.Client(project=project_id)

# Query data based on condition from the table
query = f"""
    SELECT *
    FROM `{project_id}.{dataset_name}.{table_name}`
"""

query_job = bigquery_client.query(query)
results = query_job.result()

restaurant_df = query_job.to_dataframe()

restaurant_df.duplicated()

restaurant_df.head()

column_sums = restaurant_df.sum()
column_sums

# 选择除 'business_id' 外的所有category相关的列
categories_df = restaurant_df.filter(like='category_')

# 计算每列的总和
column_sums = categories_df.sum()

# 定义阈值
threshold = 10

# 过滤出总和低于阈值的列
columns_to_drop = column_sums[column_sums < threshold].index

# 删除这些列
restaurant_df_edited = restaurant_df.drop(columns=columns_to_drop)

# 显示结果或继续处理
restaurant_df_edited.head()

destination_table = 'restaurant_dataset.food_df_edited'
project_id = 'whyso-project-0621'

# Use the to_gbq function to upload the DataFrame (after data processing) to BigQuery
restaurant_df_edited.to_gbq(destination_table, project_id=project_id, if_exists='replace', progress_bar=True)

